export default [
    {
        path:'/',
        component:()=>import('@/views/main'),
        children:[
            {
                path:'/newProject',
                name:'newProject',
                component:()=>import('@/views/main/projectManagement/newProject'),
                redirect:'/newProject/projectChild',
                children:[
                    {
                        path:'/newProject/projectChild',
                        name:'projectChild',
                        component:()=>import('@/views/main/projectManagement/newProject/projectChild')
                    },
                    {
                        path:'/newProject/projectEdit',
                        name:'projectEdit',
                        component:()=>import('@/views/main/projectManagement/newProject/projectEdit')
                    }
                ]
            },
            {
                path:'/newUser',
                name:'newUser',
                component:()=>import('@/views/main/userManagement/newUser'),
                redirect:'/newUser/buildUser',
                children:[
                    {
                        path:'/newUser/buildUser',
                        name:'buildUser',
                        component:()=>import("@/views/main/userManagement/newUser/buildUser")
                    },
                    {
                        path:'/newUser/editUser',
                        name:'editUser',
                        component:()=>import("@/views/main/userManagement/newUser/editUser")
                    },
                ]
            },
            {
                path:'/newMagnum',
                name:'newMagnum',
                component:()=>import('@/views/main/dataManagement/newMagnum'),
                redirect:'/newMagnum/buildData',
                children:[
                    {
                        path:'/newMagnum/buildData',
                        name:'buildData',
                        component:()=>import('@/views/main/dataManagement/newMagnum/buildData')
                    },
                    {
                        path:'/newMagnum/editData',
                        name:'buildData',
                        component:()=>import('@/views/main/dataManagement/newMagnum/editData')
                    }
                ]
            },
            {
                path:'/newFunction',
                name:'newFunction',
                component:()=>import('@/views/main/functionManagement/newFunction'),
                redirect:'/newFunction/functionEdit',
                children:[
                    {
                        path:'/newFunction/functionEdit',
                        name:'functionEdit',
                        component:()=>import('@/views/main/functionManagement/newFunction/functionEdit')
                    },
                    {
                        path:'/newFunction/configFunction',
                        name:'functionEdit',
                        component:()=>import('@/views/main/functionManagement/newFunction/configFunction')
                    }
                ]
            },
            {
                path:'/newLabel',
                name:'newLabel',
                component:()=>import('@/views/main/functionManagement/newLabel'),
                redirect:'/newLabel/buildLabel',
                children:[
                    {
                        path:'/newLabel/buildLabel',
                        name:'buildLabel',
                        component:()=>import('@/views/main/functionManagement/newLabel/buildLabel')
                    },
                    {
                        path:'/newLabel/editLabel',
                        name:'editLabel',
                        component:()=>import('@/views/main/functionManagement/newLabel/editLabel')
                    }
                ]
            },
            {
                path:'/newInformation',
                name:'newInformation',
                component:()=>import('@/views/main/systemManagement/newInformation'),
                children:[
                    {
                        path:'/newInformation/buildInformation',
                        component:()=>import('@/views/main/systemManagement/newInformation/buildInformation')
                    },
                    {
                        path:'/newInformation/editInformation',
                        component:()=>import('@/views/main/systemManagement/newInformation/editInformation')
                    }
             
                ]
            },
            {
                path:'/newRole',
                name:'newRole',
                component:()=>import('@/views/main/systemManagement/newRole'),
                children:[
                    {
                        path:'/newRole/buildRole',
                        component:()=>import('@/views/main/systemManagement/newRole/buildRole')
                    },
                    {
                        path:'/newRole/editRole',
                        component:()=>import('@/views/main/systemManagement/newRole/editRole')
                    },
                    {
                        path:'/newRole/configAuthority',
                        component:()=>import('@/views/main/systemManagement/newRole/configAuthority')
                    },
                ]
            },
            {
                path: "/keywordManagement",
                name: "keywordManagement",
                component: () =>
                import(
                    "@/views/main/projectManagement/keywordManagement"
                )
            
            }
        
        ]
    },
]